### ISSUE TITLE
observability-bundle Helm releases left behind on CAPA MC

### ISSUE THREAD

**Issue by AndiDog** [giantswarm/roadmap#3182] opened 2024-01-24 11:08 UTC
Most of these belong to deleted clusters and should have been cleaned up. Maybe there's a race condition cleaning this up while the respective WC is already deleting/deleted.

```sh
$ helm ls -n org-giantswarm -a # MC=golem
NAME                          	NAMESPACE     	REVISION	UPDATED                                	STATUS  	CHART                      	APP VERSION
b6z4i-observability-bundle    	org-giantswarm	1       	2023-12-11 08:40:47.252626918 +0000 UTC	deployed	observability-bundle-0.8.5
berktest-observability-bundle 	org-giantswarm	8       	2024-01-08 13:43:27.042828297 +0000 UTC	deployed	observability-bundle-0.10.1
berktest2-observability-bundle	org-giantswarm	3       	2024-01-05 09:23:25.993186292 +0000 UTC	deployed	observability-bundle-0.10.1
berktest3-observability-bundle	org-giantswarm	3       	2024-01-05 11:22:12.211719827 +0000 UTC	deployed	observability-bundle-0.10.1
berktest5-observability-bundle	org-giantswarm	2       	2024-01-15 14:00:10.946592206 +0000 UTC	deployed	observability-bundle-1.0.0
cg57t-observability-bundle    	org-giantswarm	2       	2023-12-12 09:51:39.633969142 +0000 UTC	deployed	observability-bundle-0.8.5
e2h5u-observability-bundle    	org-giantswarm	2       	2023-12-18 15:28:03.270422622 +0000 UTC	deployed	observability-bundle-0.8.5
e6k2a-observability-bundle    	org-giantswarm	2       	2023-12-11 15:24:16.605658598 +0000 UTC	deployed	observability-bundle-0.8.5
fk5t7-observability-bundle    	org-giantswarm	2       	2023-12-25 13:50:10.329738685 +0000 UTC	deployed	observability-bundle-0.8.5
golem                         	org-giantswarm	13784   	2023-12-13 15:49:25.631928978 +0000 UTC	deployed	cluster-aws-0.53.0
golem-app-operator            	org-giantswarm	14      	2023-11-15 08:53:44.334268055 +0000 UTC	deployed	app-operator-6.10.0        	6.10.0
golem-default-apps            	org-giantswarm	73      	2024-01-23 12:22:52.739223524 +0000 UTC	deployed	default-apps-aws-0.40.0
golem-observability-bundle    	org-giantswarm	22      	2024-01-23 15:55:21.313969437 +0000 UTC	deployed	observability-bundle-0.10.1
h7n4w                         	org-giantswarm	1       	2023-11-14 10:26:44.081391072 +0000 UTC	deployed	cluster-aws-0.48.1
n6z5q-observability-bundle    	org-giantswarm	1       	2023-12-11 14:29:11.901687809 +0000 UTC	deployed	observability-bundle-0.8.5
pau002-observability-bundle   	org-giantswarm	2       	2023-12-05 11:13:53.62797726 +0000 UTC 	deployed	observability-bundle-0.10.1
stef1-observability-bundle    	org-giantswarm	1       	2023-12-20 10:55:45.0718291 +0000 UTC  	deployed	observability-bundle-0.10.1
vac0df2-observability-bundle  	org-giantswarm	1       	2024-01-03 11:49:01.957385159 +0000 UTC	deployed	observability-bundle-0.10.1
vac0df3-observability-bundle  	org-giantswarm	1       	2024-01-03 15:07:27.663572202 +0000 UTC	deployed	observability-bundle-0.10.1
vac0fin-observability-bundle  	org-giantswarm	1       	2024-01-03 09:15:54.528682537 +0000 UTC	deployed	observability-bundle-0.10.1
vac0r-observability-bundle    	org-giantswarm	3       	2024-01-05 08:12:39.667174021 +0000 UTC	deployed	observability-bundle-0.8.5
vac0t-observability-bundle    	org-giantswarm	3       	2023-12-11 08:58:08.138405011 +0000 UTC	deployed	observability-bundle-0.8.5
vacmig04-observability-bundle 	org-giantswarm	1       	2024-01-12 09:48:26.397679813 +0000 UTC	deployed	observability-bundle-0.10.1
vacmig10-observability-bundle 	org-giantswarm	1       	2024-01-17 14:19:07.51804453 +0000 UTC 	deployed	observability-bundle-0.10.1
w2wx6-observability-bundle    	org-giantswarm	1       	2023-12-07 11:08:29.168948767 +0000 UTC	deployed	observability-bundle-0.8.5
wario17-observability-bundle  	org-giantswarm	1       	2024-01-15 15:42:37.568958282 +0000 UTC	deployed	observability-bundle-0.10.1
wario22-observability-bundle  	org-giantswarm	1       	2024-01-16 08:27:14.761675072 +0000 UTC	deployed	observability-bundle-0.10.1
wario32-observability-bundle  	org-giantswarm	3       	2024-01-23 09:04:02.036036886 +0000 UTC	deployed	observability-bundle-1.0.0
wv95i-observability-bundle    	org-giantswarm	2       	2023-12-30 09:50:51.047276052 +0000 UTC	deployed	observability-bundle-0.10.1
```

**Comment by QuentinBisson** [comment] 2024-01-25 10:32
This is a duplicate of https://github.com/giantswarm/giantswarm/issues/25887

**Comment by QuentinBisson** [comment] 2024-01-25 10:33
@ljakimczuk should this not have been fixed in cluster-operator?

**Comment by QuentinBisson** [comment] 2024-02-06 08:55
Closing as duplicate but I'm a bit confused as I thought it was fixed

**Closed by QuentinBisson** 2024-02-06 08:55 UTC
Labels: team/atlas
