### ISSUE TITLE
Avoid running Dex in a fork

### ISSUE THREAD

**Issue by snizhana-dynnyk** [giantswarm/roadmap#630] opened 2021-12-09 20:19 UTC
### Description

We are running a fork of Dex atm because we rely on support for the prefixing of group names with automatic id. These changes were declined upstream because they plan to implement middleware and design is far from being something that contributors agreed on. 

Changes proposed upstream - https://github.com/dexidp/dex/pull/2051
Alternative - https://github.com/giantswarm/giantswarm/issues/16933 Find a solution to avoid 'customer:' group name prefix 

### TODO

- [ ] try to bring our contributions upstream

**Comment by marians** [comment] 2022-02-18 15:51
The upstream issue this is related to is

- https://github.com/dexidp/dex/issues/918

**Comment by marians** [comment] 2022-02-21 10:03
I just checked on the status upstream. It seems as if connector middlewares (which were the reason our PR was "rejected" or put on ice) don't have progressed at all.

@puja108 You [commented](https://github.com/dexidp/dex/issues/918#issuecomment-791323986) there almost a year ago. Would it make sense if you could try again? Or should someone else?

The aspects we could mention are

- Our implementation is tested in production with several connectors.
- Middlewares have not progressed. Once they are here, the implementation could off course be changed.

**Comment by puja108** [comment] 2022-02-21 11:07
I'd prefer if you or someone from Rainbow would continue the conversation, so you can steer it better in the right direction. I would then still be available to +1 and/or escalate (and can take that role better then).

**Comment by marians** [comment] 2022-02-21 11:16
ACK, done

**Comment by anvddriesch** [comment] 2022-05-24 13:28
Let's try again to contribute upstream now that all connectors work with prefixing.

**Comment by jonaz** [comment] 2024-03-20 22:02
Did you manage to get this upstream?

**Comment by anvddriesch** [comment] 2024-03-21 07:04
@jonaz unfortunately not. We were told that it might be part of https://github.com/dexidp/dex/issues/1635 but the issue is still open.

**Comment by jonaz** [comment] 2024-03-21 09:02
i did remind them here: https://github.com/dexidp/dex/issues/918#issuecomment-2011680310

**Comment by gawertm** [comment] 2024-04-30 12:45
no news upstream for 2 years, not sure if we are going to use dex in the future anyways, closing for now. will revisit when discussing future of Dex

**Closed by gawertm** 2024-04-30 12:45 UTC
Labels: component/dex, epic/managed-dex
