### ISSUE TITLE
Scheduled GitHub action of cluster-api fork fails because we don't have the previous release branches

### ISSUE THREAD

**Issue by AndiDog** [giantswarm/roadmap#2787] opened 2023-08-31 07:57 UTC
Run: https://github.com/giantswarm/cluster-api/actions/runs/6024541052

Since we only care about the latest release branch in the fork, we should tweak or disable the action.

Could also be done by Turtles if we want to hand the project ownership over immediately. Ask @AndiDog questions about the fork if needed 😉

**Comment by T-Kukawka** [comment] 2023-08-31 08:53
@Rotfuks can u discuss this in your team? Issue is with the cluster-api which is shared across providers

**Comment by AndiDog** [comment] 2023-10-16 11:00
PR checks such as `verify PR contents` also don't make sense in the fork. Guess we have to mostly replace `.github/`.

**Comment by weseven** [comment] 2023-12-18 09:39
Opened PR: https://github.com/giantswarm/cluster-api/pull/20

**Comment by weseven** [comment] 2023-12-18 16:31
Merged, monitoring next action fails.

**Comment by weseven** [comment] 2023-12-28 10:20
Actions no longer check for previous release branches (that are not in our fork).
"Weekly security scan" and "Weekly check all Markdown links" currently fail on main branch but that is the expected behavior since they identify some issue.

**Closed by weseven** 2023-12-28 10:20 UTC
Labels: area/kaas, kind/task, topic/capi, provider/none, team/turtles
