### ISSUE TITLE
ssh access to CAPO cluster nodes

### ISSUE THREAD

**Issue by cornelius-keller** [giantswarm/roadmap#622] opened 2021-12-07 14:18 UTC
- [ ] setup (central) vault or use operations vault
- [ ] setup bastion hosts
- [ ] Modify CAPO bastions to take certificates instead of keys

**Comment by kopiczko** [comment] 2021-12-15 19:15
Dupe of https://github.com/giantswarm/roadmap/issues/634

**Closed by kopiczko** 2021-12-15 19:15 UTC
Labels: area/empowerment, area/kaas, team/rocket, epic/capo
