### ISSUE TITLE
Include loki & promtail into monitoring + alerting

### ISSUE THREAD

**Issue by ubergesundheit** [giantswarm/roadmap#355] opened 2021-06-21 13:36 UTC
Loki + Promtail should be included in Giant Swarm monitoring

**Comment by snizhana-dynnyk** [comment] 2022-01-24 19:49
closing as a duplicate of https://github.com/giantswarm/roadmap/issues/718 and https://github.com/giantswarm/roadmap/issues/722

**Closed by snizhana-dynnyk** 2022-01-24 19:49 UTC
Labels: feature-request, team/atlas
