### ISSUE TITLE
Prevent GitOps-managed resources from being edited in the web UI

### ISSUE THREAD

**Issue by kuosandys** [giantswarm/roadmap#1177] opened 2022-06-21 07:54 UTC
Towards https://github.com/giantswarm/roadmap/issues/624.

This is the issue tracking the implementation of the specs from https://github.com/giantswarm/roadmap/issues/1176

**Comment by gusevda** [comment] 2022-09-20 08:28
Closing as a duplicate of https://github.com/giantswarm/roadmap/issues/624

**Closed by gusevda** 2022-09-20 08:28 UTC
Labels: epic/gitops, ui/web-ui, team/rainbow
