### ISSUE TITLE
Add support for access to workload clusters via the Management API

### ISSUE THREAD

**Issue by snizhana-dynnyk** [giantswarm/roadmap#116] opened 2020-04-16 14:10 UTC
Towards #90 Migrate GS API to Kubernetes API 

## Rationale

With the Giant Swarm REST API it was possible to create a certificate via `gsctl create kubeconfig` to access a workload cluster.
As the Giant Swarm REST API has been deprecated, we need to support this via the Management API.

Currently, it is done by `cluster-service` speaking with `vault`.

## User Story

- _As a Giant Swarm user, I want to be able to create credentials so that I can access a workload cluster without being authenticated_

## Dependencies

Ludacris is currently working on certificates being issued from Kubernetes itself instead of `vault`.
After this, it will be possible to take certificates out from the Tenant Clusters itself.
 - [ ] #50 Certificate generation/rotation for individual k8s components

**Comment by cornelius-keller** [comment] 2020-05-07 08:32
I had a quick look in the CAPI documentation. For now CAPI generates only one kubeconfig for the cluster admin and puts it in a secret in the management cluster. There is no documented way to create more user specific kubeconfigs. 
So we need to decide if try to work on a sulution with upstream or work on our own solution first.

**Comment by snizhana-dynnyk** [comment] 2020-05-07 08:51
> we need to decide if try to work on a solution with upstream or work on our own solution first.

@giantswarm/wg-control-plane-api @giantswarm/sig-architecture wdyt guys, how should we approach this?

**Comment by JosephSalisbury** [comment] 2020-05-07 09:06
@cornelius-keller how is the cluster admin kubeconfig created?

**Comment by cornelius-keller** [comment] 2020-05-07 10:12
I have to look into the details. As far as I understand this for now the
capi cluster operator just creates the kubeconfig along with all the other
needed certificates and secrets on cluster creation.
See
https://cluster-api.sigs.k8s.io/developer/architecture/controllers/cluster.html?highlight=kubeconfig#secrets

**Comment by JosephSalisbury** [comment] 2020-05-07 10:24
That's kind of disappointing. We might need to push a little here :D

We had some story towards things we were lacking in our certificate support, I assume this should / would fold into there

**Comment by puja108** [comment] 2020-05-11 12:13
Not sure if it should fold into ludacris' issue, but depending on how that one gets implemented might need to at least have an MVP of this folded in.

Rough idea (assuming we would enable K8s CSR functionality for TCs) would be to expose the TC internal CSR logic towards the CP in a controlled manner:
1. A user asks some "thing" A in the CP to put in a CSRs to a TC
2. Some "thing" B accepts the CSR based on some logic
3. Some "thing" A reads the now filled CSR and exposes the cert to user

Notes:
- A and B can be the same "thing" but logically aren't, as B is the global "accepter" of CSRs to automate admin tasks and A is just one of many "requesters"
- A might only need to be able to get cluster-admin certs, as any other cert could also be created by talking to the TC API directly using a cluster-admin cert and we should anyway push users towards not using certs but going for OIDC for authn.
- Midterm, we ourselves should also have our own OIDC provider attached to TCs so that we do not need any certs for ourselves.
- In that line of reasoning and in line with thoughts on CP OIDC we should aim to have OIDC-only and retire certs for users. For customers without OIDC compliant IdPs we could think of providing a workaround based on github or sth.

**Comment by snizhana-dynnyk** [comment] 2020-05-14 10:15
From wg cp api sync - all customers with access to CP API are asking about accessing TCs using `kubeconfig`, they don't consider OIDC as a default method.

**Comment by teemow** [comment] 2020-05-29 09:51
fyi @jgsqware

**Comment by puja108** [comment] 2020-11-25 13:29
I was thinking we might want to rethink the user story here. I think it can be misleading, how we put it, cause what the customer wants is to get access to the tenant clusters in the case that they do not have or cannot use OIDC for a certain user. If access is granted through a certificate, a token, or something else is not really of concern to the user as long as it works similarly to how they are using it now, i.e. within a kubeconfig, and has the required features, e.g. setting TTL, username, groups. So I would remove the mentioning of "certificate" from the title and user story and reframe it on the actual Job to be done, which could also be clarified more with current customers. WDYT?

**Comment by puja108** [comment] 2021-04-28 14:16
We researched this some more and since we are moving all customers to OIDC/SSO access, we would like to keep that mode of authentication as the preferred and most secure way.

All the while we keep Service Accounts as a mode of authentication that users can manage from within the Workload Cluster.

Furthermore, with our move towards Cluster API we will most probably enabnle CSR functionality inside the Workload Clsuters, which can be used to create certificates from within the Workload Cluster.

OIDC being the more secure should remain our default and preferred mode. Using SAs or CSRs from within a Workload Cluster is a workaround that we should officially document (or link to upstream documentation as they are native functionality). The only minor downside being a switch from Management API to Workload Cluster API for creating those, which should be fine as most use cases should support the OIDC authentication setup. Latter, needs to be confirmed with customers.

**Comment by snizhana-dynnyk** [comment] 2021-06-17 10:24
We need to sort out GS access, @puja108 is aware

**Comment by puja108** [comment] 2021-06-18 08:59
We need to start documenting the SA way of getting credentials for SSO/MAPI only customers even before CAPI.

Additionally, we need to think about what happens to GS own access when the Rest API gets killed, with CAPI we said we have the CAPI kubeconfig that for now we could use. Ideally we could also use OIDC, but that might be a huge story by itself, as we need to support 1 GS IdP for all but maybe 1 customer IdP per cluster (we have that at at least one customer), so can't even be a single Dex most probably.
Might be ok to say we keep Rest API cert functionality open for GS admins until we moved everything to CAPI and only then open up this pandora's box.

**Comment by puja108** [comment] 2021-08-19 12:03
There's currently a workaround to get keypairs and kuebconfigs through the Management API and other ways of accessing workload clusters are documented.

We will, however, still need to offer a way to create keypairs/kubeconfigs programmatically going forward with Cluster API, as even if we prefer customers to not use them for day to day work there's two use cases that currently depend on this functionality and that hardly go away:
1. Additional Management Cluster components like e.g. app-operator need access to the Workload Clusters' APIs
2. The bootstrap setups of customers (at minimum for bootstrapping first RBAC roles that map to their OIDC setup) need such access.

For 2 we could build a workaround that enables WC RBAC bootstrapping and configuration through a configurable App. However, as we need the functionality still for 1 it makes sense to build it in a way that it can also be exposed to customers and not limit their possibilities and choice of tooling for bootstrapping.

**Comment by puja108** [comment] 2021-08-19 12:19
Ludacris will work on the Certificate setup for Cluster API clusters, once we're done with the more general release engineering, testing, and defaulting foundation, which is needed for quicker iterations on our Cluster API product.

With the certificate setup we will then also see to it that we have a way that programatical creation of kubeconfigs is possible from within the Mangement Cluster.

**Comment by marians** [comment] 2021-08-19 12:41
FYI The workaround @puja108 mentioned above is documented here: https://docs.giantswarm.io/ui-api/management-api/wc-key-pairs/

**Comment by marians** [comment] 2022-08-26 13:10
This issues has been sleeping for a while, and it has some overlap with other issues. I'll try to summarize the current status.

- We have `kubectl gs login` working with workload clusters both for vintage (pre Cluster API) and Cluster API.
  - The only authentication method supported here is client certificates.
  - For OIDC there is https://github.com/giantswarm/roadmap/issues/489
- We provide dex-app for workload clusters.
- We have rbac-bootstrap-app which allows to configure the initial RBAC setup in a workload cluster.

Can we close this issue? @puja108

**Comment by teemow** [comment] 2022-08-26 13:37
Yes. Let's continue in #489 then :+1:

**Closed by teemow** 2022-08-26 13:37 UTC
Labels: area/kaas, topic/management-api, team/rainbow
