### ISSUE TITLE
Replace `docker.io` with the new registry in the `cluster-vsphere` chart

### ISSUE THREAD

**Issue by alex-dabija** [giantswarm/roadmap#3246] opened 2024-02-19 12:26 UTC
## Task

Replace `docker.io` with the new registry in the `cluster-vsphere` chart.

## Links
- [Epic](https://github.com/giantswarm/roadmap/issues/2882);
- [State after initial investigation on CAPA](https://github.com/giantswarm/roadmap/issues/2882#issuecomment-1884849813).

**Comment by glitchcrab** [comment] 2024-02-23 11:20
dupe of https://github.com/giantswarm/roadmap/issues/3245

**Closed by glitchcrab** 2024-02-23 11:20 UTC
Labels: area/kaas, team/rocket, topic/capi
