### ISSUE TITLE
Webhooks for events

### ISSUE THREAD

**Issue by cornelius-keller** [giantswarm/roadmap#74] opened 2020-02-18 05:43 UTC
## User story

* As a cluster admin I'd like to hook up my deployment pipeline to a new cluster and automate the installation of basic components or configuration on the new cluster.

* As a cluster admin, I want an automation to be started whenever a workload cluster is deleted, so I can initiate the removal of custom AWS resources (e. g. security groups) linked to the workload cluster's VPC, which would otherwise remain in place, create cost, and prevent the deletion of the workload cluster.

## Rationale

Create a hook system that lets people automate their Kubernetes cluster operations.

Use case example: Set up a standard set of manifests as soon as a cluster has been created, e. g. to set up RBAC roles, network policies.

## Background

Analog to event stream, but as hooks that the customer can react on.

## Dependencies/prerequisites

- EVENT-HISTORY

## Related stories

- EVENT-STREAM

**Comment by snizhana-dynnyk** [comment] 2021-12-13 10:46
closing as a duplicate of https://github.com/giantswarm/adidas/issues/839

**Closed by snizhana-dynnyk** 2021-12-13 10:46 UTC
Labels: area/kaas, topic/observability, epic/revisit-after-capi
