### ISSUE TITLE
Access to Grafana for non admin group users

### ISSUE THREAD

**Issue by weatherhog** [giantswarm/roadmap#781] opened 2022-02-01 14:41 UTC
As a customer I want to have access to Grafana, even if I am not in the admin group.

At the moment only admin group members have access to Grafana.

- [ ] Add a second group to the corresponding OIDC provider
- [ ] Add that group to Grafana to gain access

**Comment by pipo02mix** [comment] 2022-02-02 07:00
From now on we have enabled the customer adding the group manually
```- name: GF_AUTH_GENERIC_OAUTH_ROLE_ATTRIBUTE_PATH
          value: contains(groups, 'S_ROLE_GROUP')  && 'Admin'
            || contains(groups, 'customer:SG_GS_INSTALLATION_Admin') && 'Viewer' || contains(groups,
            'customer:SG_GS_INSTALLATION_DevTL') && 'Viewer'``

**Comment by LolloneS** [comment] 2022-03-24 13:09
We are facing the same situation with another customer. It would be great to be able to have multiple groups.

**Comment by QuentinBisson** [comment] 2022-05-12 10:21
@pipo02mix for which customer did you configure it manually ? I think we can do this now by overriding https://github.com/giantswarm/config/blob/4de8b8d3d9ca3985e55e4e4a5a3c11c5d08b5a72/default/apps/grafana/configmap-values.yaml.template#L59

**Comment by QuentinBisson** [comment] 2024-03-21 08:52
This is a duplicate of this https://github.com/giantswarm/roadmap/issues/1572

**Closed by QuentinBisson** 2024-03-21 08:52 UTC
Labels: kind/story, kind/task, team/atlas, component/grafana
