### ISSUE TITLE
`kubelet` deprecation of "cloud-provider" flag

### ISSUE THREAD

**Issue by alex-dabija** [giantswarm/roadmap#2417] opened 2023-04-27 08:15 UTC
## Task

The `--cloud-provider` flag is deprecated and it will be removed. It should be replaced with [CloudProviderConfiguration](https://kubernetes.io/docs/reference/config-api/kube-controller-manager-config.v1alpha1/#cloudcontrollermanager-config-k8s-io-v1alpha1-CloudProviderConfiguration).

Logs entry:
```
Flag --cloud-provider has been deprecated, will be removed in 1.24 or later, in favor of removing cloud provider code from Kubelet.
```

## Links

- [Upstream configuration documentation](https://kubernetes.io/docs/reference/config-api/kube-controller-manager-config.v1alpha1/).

**Comment by bdehri** [comment] 2023-06-05 10:35
as I understand, from the this [pr](https://github.com/kubernetes/kubernetes/pull/91539), there is no need to anything in case of . Since we use the [flag](https://github.com/giantswarm/cluster-aws/blob/847575503248564064ef796a44f16de32cff6542/helm/cluster-aws/templates/_machine_pools.tpl#L89) in mentioned form we can close this issue. Also, `-cloudprovider=external` flag is still mentioned in the newest [docs](https://kubernetes.io/docs/tasks/administer-cluster/running-cloud-controller/#running-cloud-controller-manager).

**Comment by T-Kukawka** [comment] 2023-11-21 08:46
👋 @giantswarm/team-turtles as you are more up to date with general kubeadm topic and it is within your expertise i will drop it to ya

**Comment by Rotfuks** [comment] 2024-01-09 09:49
First outcome to aim for here: 

*   Investigate what the issue is 
*   estimate how much effort to fix now or later.

**Comment by weseven** [comment] 2024-03-18 14:41
The kubelet flag has been undeprecated in 1.29, allowing the usage of `--cloud-provider=external` as we do: https://github.com/kubernetes/kubernetes/pull/121367

The flag is still functional (with a deprecated note) in kubernetes 1.25-1.28, so no changes needed on our part.

For the sake of completeness, we specify it in the cluster chart in the init and joinconfiguration of controlplane and worker nodes, here:

https://github.com/giantswarm/cluster/blob/0bfa0e30585159d4d51f8aab916491d410024fd7/helm/cluster/templates/clusterapi/controlplane/_helpers_initconfiguration.tpl#L13
https://github.com/giantswarm/cluster/blob/0bfa0e30585159d4d51f8aab916491d410024fd7/helm/cluster/templates/clusterapi/controlplane/_helpers_joinconfiguration.tpl#L11
https://github.com/giantswarm/cluster/blob/0bfa0e30585159d4d51f8aab916491d410024fd7/helm/cluster/templates/clusterapi/workers/_helpers_joinconfiguration.tpl#L16

If anything changes in future releases of kubernetes, it should be enough to adapt those helm templates.

**Closed by weseven** 2024-03-18 14:41 UTC
Labels: area/kaas, kind/task, topic/capi, provider/cluster-api-aws, team/turtles

**Comment by nprokopic** [comment] 2024-04-18 11:46
> The kubelet flag has been undeprecated in 1.29

deprecate the deprecation 😂
