### ISSUE TITLE
Meaningful alerts based on cluster labels

### ISSUE THREAD

**Issue by gianfranco-l** [giantswarm/roadmap#645] opened 2021-12-13 17:32 UTC
As a GS engineer, 
I want to receive meaningful alerts based on cluster labels 
so that I can increase operational efficiency and productivity

Dependency: having clusters with labels, related issue [here](https://github.com/giantswarm/giantswarm/issues/15687)

**Comment by snizhana-dynnyk** [comment] 2022-01-10 16:22
closing as a dupe of https://github.com/giantswarm/roadmap/issues/688

**Closed by snizhana-dynnyk** 2022-01-10 16:22 UTC
Labels: feature-request, team/atlas, needs-refinement
