### ISSUE TITLE
Cluster resources not deleted

### ISSUE THREAD

**Issue by alex-dabija** [giantswarm/roadmap#2663] opened 2023-07-19 07:49 UTC
## Issue

Some cluster resources are not deleted when a cluster is removed.

The resources are as follows:

- configmap/{cluster_name}.default-apps-userconfig
- configmap/{cluster_name}.userconfig
- secret/{cluster_name}.bastion-ignition

The first two can be explained by not deleting the cluster as it was created (namely, deleting `App` and `ConfigMap` as generated by kubectl-gs). However, the bastion-ignition secret seems to indeed remain for CAPA clusters, with finalizer `bastion.finalizers.giantswarm.io/secret-blocker`.

**Comment by alex-dabija** [comment] 2023-07-19 07:55
@T-Kukawka Please, check if this is still an issue.

**Comment by T-Kukawka** [comment] 2023-07-19 09:19
we are not deploying the secret anymore (used for Ubuntu) - the CMs are by design, closing

**Closed by T-Kukawka** 2023-07-19 09:19 UTC
Labels: area/kaas, topic/capi, kind/bug, provider/cluster-api-aws, team/phoenix
