### ISSUE TITLE
Update Public Docs for CAPVCD

### ISSUE THREAD

**Issue by gawertm** [giantswarm/roadmap#2445] opened 2023-05-08 08:57 UTC
needed for GA. we must describe our CAPVCD offering, how it integrates with VCD and what are the VCD requirements.
Hydra is working on a similar document together with sig-docs to describe this for CAPA. we may follow the same style

**Comment by vxav** [comment] 2023-06-05 12:14
Closing as duplicate of https://github.com/giantswarm/giantswarm/issues/26593

**Closed by vxav** 2023-06-05 12:14 UTC
