### ISSUE TITLE
Enable Loki bloom filters

### ISSUE THREAD

**Issue by Rotfuks** [giantswarm/roadmap#3563] opened 2024-07-09 12:35 UTC
### Motivation

We currently have quite poor query performance, Loki bloom filters might drastically help us here.

### Todo

*   Investigate about Loki bloom filters 
*   Finetune it - be careful! 

### Outcome 

*   We have significantly better query performance on loki

**Comment by QuentinBisson** [comment] 2024-07-17 11:39
Testing on grizzly:

```yaml
data:
  values: |
    loki:
      loki:
        bloom_compactor: 
          enabled: true
        bloom_gateway: 
          enabled: true
```

**Comment by QuentinBisson** [comment] 2024-07-17 11:59
Configuration to enable blooms is here https://grafana.com/docs/loki/latest/operations/query-acceleration-blooms/

**Comment by QuentinBisson** [comment] 2024-07-17 12:58
For easier config upstream https://github.com/grafana/loki/pull/13556/files

**Comment by QuentinBisson** [comment] 2024-07-17 13:02
Blooms appear to be running:

```
level=warn ts=2024-07-17T12:39:36.982467778Z caller=experimental.go:22 component=bloom-gateway msg="experimental feature in use" feature="Bloom Gateway"
level=warn ts=2024-07-17T12:39:37.488375223Z caller=experimental.go:22 component=bloom-compactor msg="experimental feature in use" feature="Bloom Compactor"
level=info ts=2024-07-17T12:39:37.491263749Z caller=module_service.go:82 msg=starting module=bloom-store
level=info ts=2024-07-17T12:39:37.491373426Z caller=module_service.go:82 msg=starting module=bloom-gateway
level=info ts=2024-07-17T12:39:37.491635225Z caller=module_service.go:82 msg=starting module=bloom-compactor-ring
level=info ts=2024-07-17T12:39:37.491923257Z caller=basic_lifecycler.go:297 msg="instance not found in the ring" instance=loki-backend-0 ring=bloom-compactor
level=info ts=2024-07-17T12:39:37.492266324Z caller=ringmanager.go:186 msg="waiting until bloom-compactor is JOINING in the ring"
level=info ts=2024-07-17T12:39:37.492277998Z caller=ringmanager.go:190 msg="bloom-compactor is JOINING in the ring"
level=info ts=2024-07-17T12:39:38.492847692Z caller=ringmanager.go:199 msg="waiting until bloom-compactor is ACTIVE in the ring"
level=info ts=2024-07-17T12:39:38.652338707Z caller=ringmanager.go:203 msg="bloom-compactor is ACTIVE in the ring"
level=info ts=2024-07-17T12:39:38.652414572Z caller=module_service.go:82 msg=starting module=bloom-compactor
level=info ts=2024-07-17T12:39:38.652433807Z caller=bloomcompactor.go:229 component=bloom-compactor msg="running bloom compaction" workers=1
level=info ts=2024-07-17T12:39:38.828599564Z caller=bloomcompactor.go:458 component=bloom-compactor msg=compacting org_id=grizzly table=loki_index_19919 ownership=0000000000000000-1f2db590ffffffff
level=info ts=2024-07-17T12:39:38.999970954Z caller=bloom_tokenizer.go:43 msg="create new bloom tokenizer" ngramlength=4 ngramskip=1
level=info ts=2024-07-17T12:49:15.660266718Z caller=bloomcompactor.go:464 component=bloom-compactor msg="finished compacting" org_id=grizzly table=loki_index_19919 ownership=0000000000000000-1f2db590ffffffff err=null
level=info ts=2024-07-17T12:49:15.660307443Z caller=bloomcompactor.go:458 component=bloom-compactor msg=compacting org_id=grizzly table=loki_index_19919 ownership=494d429600000000-5cc2b730ffffffff
level=info ts=2024-07-17T12:49:15.781431865Z caller=bloom_tokenizer.go:43 msg="create new bloom tokenizer" ngramlength=4 ngramskip=1
level=info ts=2024-07-17T12:54:00.923802168Z caller=bloomcompactor.go:464 component=bloom-compactor msg="finished compacting" org_id=grizzly table=loki_index_19919 ownership=494d429600000000-5cc2b730ffffffff err=null
level=info ts=2024-07-17T12:54:00.923839186Z caller=bloomcompactor.go:458 component=bloom-compactor msg=compacting org_id=grizzly table=loki_index_19919 ownership=7aba04f000000000-7cab8bc3ffffffff
level=info ts=2024-07-17T12:54:01.050083204Z caller=bloom_tokenizer.go:43 msg="create new bloom tokenizer" ngramlength=4 ngramskip=1
level=info ts=2024-07-17T12:55:43.661769826Z caller=bloomcompactor.go:464 component=bloom-compactor msg="finished compacting" org_id=grizzly table=loki_index_19919 ownership=7aba04f000000000-7cab8bc3ffffffff err=null
level=info ts=2024-07-17T12:55:43.661813577Z caller=bloomcompactor.go:458 component=bloom-compactor msg=compacting org_id=grizzly table=loki_index_19919 ownership=811d50dc00000000-873fcb23ffffffff
level=info ts=2024-07-17T12:55:43.822757244Z caller=bloom_tokenizer.go:43 msg="create new bloom tokenizer" ngramlength=4 ngramskip=1
level=info ts=2024-07-17T12:57:24.761064787Z caller=bloomcompactor.go:464 component=bloom-compactor msg="finished compacting" org_id=grizzly table=loki_index_19919 ownership=811d50dc00000000-873fcb23ffffffff err=null
level=info ts=2024-07-17T12:57:24.76110158Z caller=bloomcompactor.go:458 component=bloom-compactor msg=compacting org_id=grizzly table=loki_index_19919 ownership=a2c20c1200000000-b63441e8ffffffff
level=info ts=2024-07-17T12:57:24.85186762Z caller=bloom_tokenizer.go:43 msg="create new bloom tokenizer" ngramlength=4 ngramskip=1
```

**Comment by QuentinBisson** [comment] 2024-07-17 13:27
The gateway is getting called:

level=info ts=2024-07-17T13:26:46.305059648Z caller=client.go:244 component=index-gateway msg="do FilterChunkRefs for addresses" progress=6/6 addr=100.64.125.204:9095 from=2024-07-17T12:25:00Z through=2024-07-17T13:26:00Z num_refs=17 plan="sum by (level)(count_over_time({__name__=\"avg \"} |= \"\\\"_HOSTNAME\\\":\\\"ip-10-0-243-252\\\"\" | drop __error__[1m]))" plan_hash=906130590

**Comment by QuentinBisson** [comment] 2024-07-17 14:18
So it is quite easy to play with bloom filters, but I'm not sure I would enable them yet because this is using a whole lot more CPUs:

![image](https://github.com/user-attachments/assets/91f922b6-8cda-469d-854d-c8e668661324)

**Comment by hervenicol** [comment] 2024-07-17 15:35
> For instance on grizzly and gazelle we see loki writes are using half their memory now but we go from 2 backend pods using 300 millicore of cpus to 5 backend pods using close 1 cpu each.

I'm not sure I understand, so I'll rephrase so you can correct me:
- write:
  - number pods did not change
  - uses half less RAM with bloom filters
- backend:
  - increased from 2 to 5 pods
  - increase is due to CPU
  - so it makes an increase from 2x0.3=0.6CPU to 1x5=5CPU
  - and what about the total RAM for backends?

So, it transfers some load from write pods to backend pods?
It's unexpected to see write pods RAM decreased. :thinking: 

Also, they warned me about mainly storage usage (PV and S3), and "probably a bit of RAM and CPU. The doc talks about RAM usage, but there not much mention about CPU usage. I'm quite surprised it has such an impact with our setup.

And another remark: the work on bloom filters is quite early works, they are working hard on optimizing it.

This is very interesting info we should make sure we have for the next community meetup, they may be interested with our feedback :)

**Comment by QuentinBisson** [comment] 2024-07-17 15:50
Yes you understood correctly :)

It's possible the memory drop for Loki write is due to the pod restarts and we can check if it's still low after a few hours.

Regarding cpu, i'm not really sure where it's coming from

Now they do not send any data to object storage from what i've seen so i'm not sure why the cost should increase.

It's possible the compactor (every 10m) but maybe we can pair on it tomorrow once i'm back from the therapist to dig deeper? You Can also check on grizzly if you want :)

**Comment by QuentinBisson** [comment] 2024-07-17 16:57
Reading the logs I think the bloom compactor is using most of the cpu at startup

**Comment by QuentinBisson** [comment] 2024-07-18 10:30
Blooms are indeed stored in azure storage

![Image](https://github.com/user-attachments/assets/b7cd581a-fd6c-49f5-9eb1-e2e56d7b9d7d)

**Comment by QuentinBisson** [comment] 2024-07-18 10:32
I tried to run it on glippy and cpu does spike for a bit but it is resolved pretty fast so I think this is related to the amout of data:


![Image](https://github.com/user-attachments/assets/ba37484b-3053-4cbd-bb3a-68121c96cba7)

**Comment by QuentinBisson** [comment] 2024-07-18 11:59
Ok I created an upstream issue https://github.com/grafana/loki/issues/13571

I think the issue is that the n-grams are recreated when the pod restarts and not stored somewhere

**Comment by QuentinBisson** [comment] 2024-07-18 12:09
I think we could enable it by adding cpu limits to less than 500m at the risk of cpu throttling?

**Comment by hervenicol** [comment] 2024-07-18 14:17
> I think we could enable it by adding cpu limits to less than 500m at the risk of cpu throttling?

Would it prevent HPA action?
Because IMO the biggest problem is not that it uses CPU at startup, but the side-effects: scaling up to twice the number of backend pods, then scaling down after a while... that will disturb resource allocations for way longer than the CPU peak.

**Comment by QuentinBisson** [comment] 2024-07-18 14:31
🤔 no it will not

**Comment by Rotfuks** [comment] 2024-07-22 12:59
So what's the options that we have here?   
\- Keep it disabled and not have the benefits of reduced RAM usage until the issue with the CPU usage spike in the beginning is fixed by upstream.  
\- Enable it and Limit the CPU Usage to handle the CPU usage spike in the startup process. But this will confuse our HPA and make Loki potentially scale up in every startup. 

What else can we do here?

**Comment by marieroque** [comment] 2024-07-23 13:34
⚠ Loki on `grizzly` was broken because of `bloom` activation.
I disabled the `loki-user-values` where the bloom compactor and the bloom gateway was activated and loki was running again properly.

It seems there is an impact on the gateway and the multi tenant proxy authentication:
https://gigantic.slack.com/archives/C07DNE8GUPL

**Comment by QuentinBisson** [comment] 2024-07-23 14:51
I added my thoughts in the incident channel but nothing points to the issue being related to bloom filters though.

**Comment by QuentinBisson** [comment] 2024-07-26 08:46
So if I read this right: https://github.com/grafana/loki/issues/12751#issuecomment-2252127654
I think it's way too early for us to enable bloom filters. @hervenicol what do you think about this ?

**Comment by hervenicol** [comment] 2024-07-26 10:28
> So if I read this right: [grafana/loki#12751 (comment)](https://github.com/grafana/loki/issues/12751#issuecomment-2252127654) I think it's way too early for us to enable bloom filters. @hervenicol what do you think about this ?

And the next message (https://github.com/grafana/loki/issues/12751#issuecomment-2252138818) confirms it:
bloom filters are under heavy development, architecture may still change quite often/fast, documentation is not guaranteed up-to-date, nobody knows about performance yet...

That's basically what they told me during community meet and I wrote here: https://gigantic.slack.com/archives/C01176DKNP4/p1720100503733899?thread_ts=1720095972.878129&cid=C01176DKNP4
...but in a more "stop complaining when messing around with experimental code" way :rofl: 

I think it's nice that we tried it,
it's nice if we have an easy way to enable it for further tests later (even though we may need to change the config),
but it's probably too early to run it by default yes.

**Comment by QuentinBisson** [comment] 2024-07-26 11:00
Well the messages are a bit différent from thé try it out définition I was thinking of because they ask for feedback and complain that they have some they did not expect 🤣

In a way, they should bé happy that people want to engage with their stuff and give reviews 😅

**Comment by QuentinBisson** [comment] 2024-07-26 11:07
So I think we can close it once i've documented how to enable them and we see later what to do

**Comment by QuentinBisson** [comment] 2024-07-26 13:11
Closing PR https://github.com/giantswarm/loki-app/pull/344

**Closed** 2024-07-30 08:53 UTC
Labels: blocked, team/atlas, needs/refinement
